### ISSUE TITLE
Out of date 

### ISSUE THREAD

**Issue by starboarder2001** [docusign/eg-01-python-jwt#6] opened 2019-07-15 23:32 UTC
This code is way out of date and not useful.  Please update.

**Comment by LarryKlugerDS** [comment] 2019-09-03 17:33
Hi, Sorry for the delay. The DocuSign Engineering team has this issue on their plan, but unfortunately we don't yet have a date. I'm sorry for the delay on this. 

Please join issue #4 -- I am marking this issue as a duplicate of issue #4 .

Thank you,
Larry

**Closed** 2019-09-03 17:34 UTC
Labels: DEVDOCS-1362, bug, duplicate
