### ISSUE TITLE
Needs to be updated!

### ISSUE THREAD

**Issue by icgranger9** [docusign/eg-01-python-jwt#7] opened 2019-07-23 21:44 UTC
Can we please get an updated version of this guide? It's way out of date.

**Comment by LarryKlugerDS** [comment] 2019-09-03 17:34
Hi, Sorry for the delay. The DocuSign Engineering team has this issue on their plan, but unfortunately we don't yet have a date. I'm sorry for the delay on this.

Please join issue #4 -- I am marking this issue as a duplicate of issue #4 .

Thank you,
Larry

**Closed** 2019-09-03 17:35 UTC
Labels: DEVDOCS-1362, bug, duplicate
